<a href="https://colab.research.google.com/github/SoheeKim12/Python_Programming_Study/blob/main/pandas_exercises/05_Merge/Housing%20Market/Exercises_sh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd
import numpy as np

### Step 2. Create 3 differents Series, each of length 100, as follows:
1. The first a random number from 1 to 4
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [3]:
series1 = np.random.randint(1, 5, size=100)
series2 = np.random.randint(1, 4, size=100)
series3 = np.random.randint(10000, 30001, size=100)

In [6]:
series3

array([15422, 24488, 20441, 10616, 19349, 10348, 20811, 10748, 20360,
       19623, 13607, 17901, 16274, 16668, 11204, 19234, 18895, 11368,
       25357, 20356, 13769, 13614, 25531, 14057, 23681, 14471, 29440,
       29799, 14504, 16418, 25264, 25377, 18673, 12932, 24869, 24611,
       20117, 12576, 11629, 17626, 11344, 10472, 21427, 14108, 21354,
       13995, 13373, 25115, 29360, 20392, 16863, 19493, 25070, 26378,
       13287, 18831, 25020, 24990, 22419, 17080, 12635, 19361, 27262,
       14201, 16493, 18226, 17604, 21191, 24124, 26996, 23281, 17081,
       10208, 26215, 10515, 22626, 26635, 21027, 20754, 20747, 17116,
       12695, 21095, 11765, 13113, 13125, 26824, 22600, 19809, 12197,
       10056, 16077, 12726, 23586, 15061, 11761, 29826, 11642, 29947,
       21959])

### Step 3. Let's create a DataFrame by joinning the Series by column

In [11]:
df = pd.DataFrame({'0':series1, '1':series2, '2':series3})

In [13]:
df.head()

   0  1      2
0  4  3  15422
1  4  2  24488
2  2  3  20441
3  4  1  10616
4  1  1  19349

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [14]:
df.columns = ['bedrs', 'bathrs', 'price_sqr_meter']

In [15]:
df.head()

   bedrs  bathrs  price_sqr_meter
0      4       3            15422
1      4       2            24488
2      2       3            20441
3      4       1            10616
4      1       1            19349

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [20]:
bicolumn = pd.concat([pd.Series(series1), pd.Series(series2), pd.Series(series3)], axis=0)

In [23]:
# Set the display option to show all rows and columns without truncation
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns (if you have multiple columns)
pd.set_option('display.expand_frame_repr', False)  # Prevent wrapping to a new line

bicolumn

0         4
1         4
2         2
3         4
4         1
5         1
6         3
7         2
8         1
9         4
10        2
11        2
12        1
13        3
14        4
15        3
16        1
17        4
18        3
19        2
20        1
21        2
22        1
23        3
24        4
25        3
26        2
27        2
28        3
29        3
30        2
31        4
32        4
33        4
34        1
35        2
36        2
37        3
38        3
39        4
40        2
41        1
42        4
43        2
44        4
45        1
46        3
47        1
48        3
49        1
50        2
51        2
52        4
53        1
54        1
55        4
56        2
57        1
58        3
59        4
60        3
61        2
62        4
63        2
64        1
65        4
66        4
67        3
68        1
69        3
70        3
71        1
72        3
73        4
74        4
75        4
76        2
77        2
78        2
79        2
80        4
81        1
82        4
83        3
84        1
85        1
86        1
87        3
88        2
89        2
90        1
91        1
92        1
93        4
94        2
95        2
96        4
97        4
98        4
99        4
0         3
1         2
2         3
3         1
4         1
5         3
6         1
7         3
8         3
9         2
10        2
11        1
12        1
13        1
14        2
15        2
16        3
17        3
18        2
19        1
20        2
21        1
22        2
23        3
24        1
25        1
26        1
27        1
28        3
29        1
30        1
31        2
32        1
33        1
34        3
35        1
36        2
37        2
38        1
39        2
40        3
41        1
42        3
43        2
44        1
45        1
46        1
47        1
48        3
49        3
50        2
51        3
52        2
53        3
54        3
55        3
56        1
57        3
58        3
59        1
60        2
61        2
62        2
63        1
64        1
65        3
66        2
67        2
68        3
69        3
70        1
71        3
72        2
73        1
74        2
75        2
76        3
77        3
78        3
79        2
80        1
81        3
82        1
83        3
84        2
85        1
86        2
87        1
88        3
89        2
90        3
91        3
92        2
93        2
94        2
95        3
96        1
97        1
98        2
99        2
0     15422
1     24488
2     20441
3     10616
4     19349
5     10348
6     20811
7     10748
8     20360
9     19623
10    13607
11    17901
12    16274
13    16668
14    11204
15    19234
16    18895
17    11368
18    25357
19    20356
20    13769
21    13614
22    25531
23    14057
24    23681
25    14471
26    29440
27    29799
28    14504
29    16418
30    25264
31    25377
32    18673
33    12932
34    24869
35    24611
36    20117
37    12576
38    11629
39    17626
40    11344
41    10472
42    21427
43    14108
44    21354
45    13995
46    13373
47    25115
48    29360
49    20392
50    16863
51    19493
52    25070
53    26378
54    13287
55    18831
56    25020
57    24990
58    22419
59    17080
60    12635
61    19361
62    27262
63    14201
64    16493
65    18226
66    17604
67    21191
68    24124
69    26996
70    23281
71    17081
72    10208
73    26215
74    10515
75    22626
76    26635
77    21027
78    20754
79    20747
80    17116
81    12695
82    21095
83    11765
84    13113
85    13125
86    26824
87    22600
88    19809
89    12197
90    10056
91    16077
92    12726
93    23586
94    15061
95    11761
96    29826
97    11642
98    29947
99    21959
dtype: int64

### Step 6. Oops, it seems it is going only until index 99. Is it true?

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [28]:
bicolumn = bicolumn.reset_index(drop=True)

bicolumn

0          4
1          4
2          2
3          4
4          1
5          1
6          3
7          2
8          1
9          4
10         2
11         2
12         1
13         3
14         4
15         3
16         1
17         4
18         3
19         2
20         1
21         2
22         1
23         3
24         4
25         3
26         2
27         2
28         3
29         3
30         2
31         4
32         4
33         4
34         1
35         2
36         2
37         3
38         3
39         4
40         2
41         1
42         4
43         2
44         4
45         1
46         3
47         1
48         3
49         1
50         2
51         2
52         4
53         1
54         1
55         4
56         2
57         1
58         3
59         4
60         3
61         2
62         4
63         2
64         1
65         4
66         4
67         3
68         1
69         3
70         3
71         1
72         3
73         4
74         4
75         4
76         2
77         2
78         2
79         2
80         4
81         1
82         4
83         3
84         1
85         1
86         1
87         3
88         2
89         2
90         1
91         1
92         1
93         4
94         2
95         2
96         4
97         4
98         4
99         4
100        3
101        2
102        3
103        1
104        1
105        3
106        1
107        3
108        3
109        2
110        2
111        1
112        1
113        1
114        2
115        2
116        3
117        3
118        2
119        1
120        2
121        1
122        2
123        3
124        1
125        1
126        1
127        1
128        3
129        1
130        1
131        2
132        1
133        1
134        3
135        1
136        2
137        2
138        1
139        2
140        3
141        1
142        3
143        2
144        1
145        1
146        1
147        1
148        3
149        3
150        2
151        3
152        2
153        3
154        3
155        3
156        1
157        3
158        3
159        1
160        2
161        2
162        2
163        1
164        1
165        3
166        2
167        2
168        3
169        3
170        1
171        3
172        2
173        1
174        2
175        2
176        3
177        3
178        3
179        2
180        1
181        3
182        1
183        3
184        2
185        1
186        2
187        1
188        3
189        2
190        3
191        3
192        2
193        2
194        2
195        3
196        1
197        1
198        2
199        2
200    15422
201    24488
202    20441
203    10616
204    19349
205    10348
206    20811
207    10748
208    20360
209    19623
210    13607
211    17901
212    16274
213    16668
214    11204
215    19234
216    18895
217    11368
218    25357
219    20356
220    13769
221    13614
222    25531
223    14057
224    23681
225    14471
226    29440
227    29799
228    14504
229    16418
230    25264
231    25377
232    18673
233    12932
234    24869
235    24611
236    20117
237    12576
238    11629
239    17626
240    11344
241    10472
242    21427
243    14108
244    21354
245    13995
246    13373
247    25115
248    29360
249    20392
250    16863
251    19493
252    25070
253    26378
254    13287
255    18831
256    25020
257    24990
258    22419
259    17080
260    12635
261    19361
262    27262
263    14201
264    16493
265    18226
266    17604
267    21191
268    24124
269    26996
270    23281
271    17081
272    10208
273    26215
274    10515
275    22626
276    26635
277    21027
278    20754
279    20747
280    17116
281    12695
282    21095
283    11765
284    13113
285    13125
286    26824
287    22600
288    19809
289    12197
290    10056
291    16077
292    12726
293    23586
294    15061
295    11761
296    29826
297    11642
298    29947
299    21959
dtype: int64